server:
  port: 5269

security:
  basic: 
    enabled: false  
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  rabbitmq:
    host: ec2-34-227-76-119.compute-1.amazonaws.com
    port: 5672
    username: user
    password: user    
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.0.1:8761/eureka/
