server:
  port: 8905
security:
  basic: 
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=Oracle
  rabbitmq:
    host: ec2-35-168-22-185.compute-1.amazonaws.com
    port: 5672
    username: user
    password: user